// ============================================
// Data Protection Scenarios
// ============================================

import type { TrainingScenario } from './types';
import { scenarioImages } from './images';

export const dataProtectionScenarios: TrainingScenario[] = [
  {
    id: 'dp-001',
    moduleType: 'data-protection',
    type: 'scenario',
    title: 'Data Classification',
    difficulty: 'beginner',
    content: {
      scenario: 'You need to classify different types of company data. Match each data type to its appropriate classification level.',
      question: 'Which classification is correct for CUSTOMER CREDIT CARD NUMBERS?',
      options: [
        { id: 'a', text: 'Public - Can be shared freely', isCorrect: false },
        { id: 'b', text: 'Internal - For employees only', isCorrect: false },
        { id: 'c', text: 'Confidential - Need-to-know basis', isCorrect: false },
        { id: 'd', text: 'Restricted/PCI - Highest protection, regulatory compliance required', isCorrect: true },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [],
    explanation: 'Credit card data falls under PCI-DSS regulations and requires the highest level of protection. It must be encrypted, access must be logged, and only personnel who need it for their job should have access. Mishandling can result in massive fines.',
    learningPoints: [
      'Payment card data is regulated by PCI-DSS',
      'Higher classification = more protection controls',
      'Regulatory data often requires specific handling procedures',
      'When in doubt, classify higher rather than lower',
    ],
    image: scenarioImages.lock,
  },
  {
    id: 'dp-002',
    moduleType: 'data-protection',
    type: 'scenario',
    title: 'Secure File Sharing',
    difficulty: 'beginner',
    content: {
      scenario: 'A client requests that you send them a document containing their account details and social security number for verification purposes.',
      question: 'What is the most secure way to send this sensitive information?',
      options: [
        { id: 'a', text: 'Attach it to a regular email', isCorrect: false },
        { id: 'b', text: 'Send via encrypted email or secure file sharing portal with access controls', isCorrect: true },
        { id: 'c', text: 'Fax the document to them', isCorrect: false },
        { id: 'd', text: 'Upload to Google Drive and share the link', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [],
    explanation: 'Sensitive PII like SSN requires encryption in transit. Use encrypted email (S/MIME, PGP) or a secure file sharing portal with access controls, expiration dates, and download tracking. Regular email, fax, and public cloud links don\'t provide adequate protection.',
    learningPoints: [
      'PII requires encryption when transmitted',
      'Use company-approved secure sharing methods',
      'Set expiration dates on shared files',
      'Verify recipient identity before sending sensitive data',
    ],
    image: scenarioImages.email,
  },
  {
    id: 'dp-003',
    moduleType: 'data-protection',
    type: 'scenario',
    title: 'Data Retention',
    difficulty: 'intermediate',
    content: {
      scenario: 'You\'re cleaning up old project files and find customer contracts from 7 years ago. The project is complete and the client relationship ended 5 years ago.',
      question: 'How should you handle these old contracts?',
      options: [
        { id: 'a', text: 'Delete them immediately to reduce data storage', isCorrect: false },
        { id: 'b', text: 'Check the data retention policy - contracts may have legal hold requirements', isCorrect: true },
        { id: 'c', text: 'Keep them forever in case they\'re needed', isCorrect: false },
        { id: 'd', text: 'Move them to your personal backup drive', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [],
    explanation: 'Data retention policies exist for legal, regulatory, and business reasons. Contracts often must be retained for specific periods (commonly 7+ years). Deleting too early can cause legal issues; keeping too long increases breach risk. Always check the retention policy.',
    learningPoints: [
      'Follow company data retention policies',
      'Different data types have different retention requirements',
      'Legal holds may prevent deletion of certain records',
      'When retention period expires, securely delete data',
    ],
    image: scenarioImages.office,
  },
  {
    id: 'dp-004',
    moduleType: 'data-protection',
    type: 'scenario',
    title: 'Working Remotely',
    difficulty: 'intermediate',
    content: {
      scenario: 'You\'re working from a coffee shop and need to review a spreadsheet containing employee salaries and performance reviews for an upcoming meeting.',
      question: 'What precautions should you take?',
      options: [
        { id: 'a', text: 'Position your screen away from others and use a privacy filter', isCorrect: false },
        { id: 'b', text: 'Wait until you\'re in a private location to view sensitive HR data', isCorrect: true },
        { id: 'c', text: 'Connect and use the bank\'s app since apps are secure', isCorrect: false },
        { id: 'd', text: 'It\'s fine since you\'re using your company laptop', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [],
    explanation: 'Highly sensitive data like salaries and performance reviews should not be viewed in public spaces. Even with privacy screens, shoulder surfing is possible, and public WiFi poses risks. This type of data should only be accessed in private, secure locations.',
    learningPoints: [
      'Some data is too sensitive for public viewing',
      'Privacy screens help but don\'t eliminate risk',
      'Public WiFi is not secure for sensitive work',
      'Consider the environment before accessing sensitive data',
    ],
    image: scenarioImages.office,
  },
  {
    id: 'dp-005',
    moduleType: 'data-protection',
    type: 'scenario',
    title: 'Disposing of Old Equipment',
    difficulty: 'intermediate',
    content: {
      scenario: 'Your department is upgrading computers. The old machines need to be disposed of. They previously contained customer data and financial records.',
      question: 'What\'s the correct way to dispose of these computers?',
      options: [
        { id: 'a', text: 'Delete all files and donate them to charity', isCorrect: false },
        { id: 'b', text: 'Format the hard drives and sell them', isCorrect: false },
        { id: 'c', text: 'Use certified data destruction (wiping or physical destruction) with documentation', isCorrect: true },
        { id: 'd', text: 'Remove the hard drives and throw them in the trash', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [],
    explanation: 'Simple deletion or formatting doesn\'t remove data - it can be recovered. Equipment that held sensitive data requires certified data destruction: either DoD-standard wiping (multiple overwrites) or physical destruction (shredding). Always get a certificate of destruction.',
    learningPoints: [
      'Deleted files can be recovered with forensic tools',
      'Formatting doesn\'t securely erase data',
      'Use certified data destruction services',
      'Obtain certificates of destruction for compliance',
      'Physical destruction is most secure for highly sensitive data',
    ],
    image: scenarioImages.security,
  },
  {
    id: 'dp-006',
    moduleType: 'data-protection',
    type: 'scenario',
    title: 'GDPR Data Request',
    difficulty: 'advanced',
    content: {
      scenario: 'A customer from Germany emails requesting a copy of all personal data your company holds about them, plus deletion of their account. Your company does business in the EU.',
      question: 'How should you respond to this request?',
      options: [
        { id: 'a', text: 'Ignore it - they can\'t make demands like that', isCorrect: false },
        { id: 'b', text: 'Forward to your Data Protection Officer/Privacy team for proper handling', isCorrect: true },
        { id: 'c', text: 'Delete their account immediately as requested', isCorrect: false },
        { id: 'd', text: 'Tell them to contact their government for their data', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [],
    explanation: 'This is a GDPR Subject Access Request (SAR) and Right to Erasure request. Under GDPR, EU citizens have legal rights to their data. These requests must be handled by trained personnel within specific timeframes (usually 30 days). Forward to your Privacy/DPO team immediately.',
    learningPoints: [
      'GDPR gives EU citizens rights over their data',
      'Subject Access Requests must be fulfilled within 30 days',
      'Forward privacy requests to designated personnel',
      'Don\'t delete data yourself - there are specific procedures',
      'Some data may need to be retained for legal reasons',
    ],
    image: scenarioImages.email,
  },
  {
    id: 'dp-007',
    moduleType: 'data-protection',
    type: 'scenario',
    title: 'Encryption Requirements',
    difficulty: 'intermediate',
    content: {
      scenario: 'You need to send a file containing customer health records to a partner organization for a joint research project.',
      question: 'What encryption requirements apply to this data?',
      options: [
        { id: 'a', text: 'No encryption needed if the partner is trustworthy', isCorrect: false },
        { id: 'b', text: 'Password protect the ZIP file before emailing', isCorrect: false },
        { id: 'c', text: 'Health data requires HIPAA-compliant encryption both in transit and at rest', isCorrect: true },
        { id: 'd', text: 'Regular HTTPS is sufficient for health data', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [],
    explanation: 'Health records are Protected Health Information (PHI) under HIPAA. They require encryption both when stored (at rest) and when transmitted (in transit). Additionally, you need a Business Associate Agreement with the partner. ZIP passwords are not HIPAA-compliant encryption.',
    learningPoints: [
      'Health data is protected by HIPAA',
      'PHI requires encryption at rest AND in transit',
      'Business Associate Agreements required for sharing PHI',
      'Use HIPAA-compliant tools (not regular email/ZIP)',
      'Document all PHI transfers',
    ],
    image: scenarioImages.lock,
  },
];
