// ============================================
// Incident Response Scenarios
// ============================================

import type { TrainingScenario } from './types';
import { scenarioImages } from './images';

export const incidentResponseScenarios: TrainingScenario[] = [
  {
    id: 'ir-001',
    moduleType: 'incident-response',
    type: 'scenario',
    title: 'Ransomware Alert',
    difficulty: 'intermediate',
    content: {
      scenario: 'It\'s Monday morning and multiple employees report they cannot access their files. Their screens display a message demanding Bitcoin payment to unlock their data. The IT help desk is flooded with calls.',
      alertDetails: {
        time: '8:47 AM',
        affectedSystems: '23 workstations',
        ransom: '5 Bitcoin ($150,000)',
        deadline: '48 hours',
      },
      question: 'What should be your FIRST action as the incident responder?',
      options: [
        { id: 'a', text: 'Pay the ransom to restore operations quickly', isCorrect: false },
        { id: 'b', text: 'Immediately disconnect affected systems from the network to contain spread', isCorrect: true },
        { id: 'c', text: 'Try to decrypt the files using online tools', isCorrect: false },
        { id: 'd', text: 'Send a company-wide email warning everyone about the attack', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [
      'Ransomware spreads laterally through networks',
      'Time pressure from ransom deadline',
      'Multiple systems affected simultaneously',
      'Payment doesn\'t guarantee data recovery',
    ],
    explanation: 'Containment is the critical first step. Disconnecting affected systems prevents the ransomware from spreading to other machines. Never pay ransoms as it funds criminals and doesn\'t guarantee recovery. After containment, escalate to leadership, preserve evidence, and begin recovery from backups.',
    learningPoints: [
      'Containment first - isolate affected systems immediately',
      'Never pay ransoms - no guarantee of recovery',
      'Preserve evidence for forensic investigation',
      'Restore from known-good backups after containment',
      'Report to law enforcement (FBI IC3)',
    ],
    image: scenarioImages.warning,
  },
  {
    id: 'ir-002',
    moduleType: 'incident-response',
    type: 'scenario',
    title: 'Suspicious Login Activity',
    difficulty: 'intermediate',
    content: {
      scenario: 'Your SIEM alerts you to unusual login activity. The CFO\'s account logged in from Russia at 2:00 AM local time, then accessed financial reports and attempted to initiate a wire transfer. The CFO is currently on vacation in Hawaii.',
      alertDetails: {
        account: 'CFO - Sarah Mitchell',
        location: 'Moscow, Russia',
        time: '2:00 AM EST',
        actions: 'Accessed Q4 financials, attempted wire transfer',
      },
      question: 'What is the most appropriate immediate response?',
      options: [
        { id: 'a', text: 'Wait to see if the wire transfer goes through before acting', isCorrect: false },
        { id: 'b', text: 'Disable the account immediately and contact the CFO through a verified channel', isCorrect: true },
        { id: 'c', text: 'Email the CFO to ask if they\'re traveling internationally', isCorrect: false },
        { id: 'd', text: 'Reset the password and send new credentials to the CFO\'s email', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [
      'Impossible travel - Hawaii to Russia in hours',
      'Off-hours access (2 AM)',
      'High-value target (CFO account)',
      'Sensitive actions (financial access, wire transfer)',
    ],
    explanation: 'This shows classic signs of account compromise. Disable the account immediately to prevent further damage. Contact the real user through verified means (phone call to known number) - never email which may also be compromised. Cancel any pending transactions.',
    learningPoints: [
      'Impossible travel is a key indicator of compromise',
      'Disable compromised accounts immediately',
      'Verify through out-of-band communication (phone)',
      'Don\'t email potentially compromised users',
      'Cancel/freeze pending financial transactions',
    ],
    image: scenarioImages.security,
  },
  {
    id: 'ir-003',
    moduleType: 'incident-response',
    type: 'scenario',
    title: 'Data Exfiltration Detection',
    difficulty: 'advanced',
    content: {
      scenario: 'Network monitoring shows an employee\'s workstation transmitted 50GB of data to an external IP address over the past week during after-hours. The destination appears to be a file-sharing service in a foreign country. The employee works in R&D.',
      alertDetails: {
        dataVolume: '50GB over 7 days',
        timing: 'After business hours (10 PM - 2 AM)',
        destination: 'External file sharing service',
        employee: 'R&D Engineer',
      },
      question: 'How should you handle this potential data breach?',
      options: [
        { id: 'a', text: 'Immediately confront the employee about the transfers', isCorrect: false },
        { id: 'b', text: 'Block the external IP and close the case', isCorrect: false },
        { id: 'c', text: 'Preserve evidence, involve HR/Legal, and conduct a discrete investigation', isCorrect: true },
        { id: 'd', text: 'Delete the employee\'s account and all their files', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [
      'Large data volume transferred externally',
      'After-hours timing suggests concealment',
      'R&D employee = access to sensitive IP',
      'Foreign destination raises concerns',
    ],
    explanation: 'This could be insider threat or compromised credentials. Preserve evidence before taking action - image the workstation, preserve logs. Involve HR and Legal before any employee interaction. Conduct discrete investigation to determine if it\'s malicious or legitimate (some employees work remotely).',
    learningPoints: [
      'Preserve evidence before taking disruptive action',
      'Involve HR and Legal for potential insider threats',
      'Don\'t alert the subject before investigation',
      'Consider legitimate explanations (remote work, large projects)',
      'Document everything for potential legal proceedings',
    ],
    image: scenarioImages.hacker,
  },
  {
    id: 'ir-004',
    moduleType: 'incident-response',
    type: 'scenario',
    title: 'Phishing Campaign Success',
    difficulty: 'intermediate',
    content: {
      scenario: 'Your email security system reports that a phishing email got through and was clicked by 47 employees. The link led to a fake Microsoft login page. You don\'t know yet who entered credentials.',
      alertDetails: {
        emailsDelivered: '1,247',
        linksClicked: '47 employees',
        fakeLoginPage: 'Microsoft 365 credential harvester',
        timeSinceAttack: '2 hours',
      },
      question: 'What is the priority response to this situation?',
      options: [
        { id: 'a', text: 'Send a company-wide email explaining phishing dangers', isCorrect: false },
        { id: 'b', text: 'Force password reset for all 47 employees who clicked and enable MFA', isCorrect: true },
        { id: 'c', text: 'Block the phishing domain and consider the incident resolved', isCorrect: false },
        { id: 'd', text: 'Identify and discipline the employees who clicked the link', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [
      '47 potential credential compromises',
      'Credential harvester page - passwords likely stolen',
      '2 hours elapsed - attackers may already be using credentials',
      'Microsoft 365 = access to email, files, Teams',
    ],
    explanation: 'Assume all 47 employees who clicked may have entered credentials. Force immediate password resets and enable MFA if not already active. Check for suspicious activity on those accounts. Block the domain, but prioritize credential protection first.',
    learningPoints: [
      'Assume credentials compromised if users visited fake login',
      'Force password resets immediately for affected users',
      'Enable MFA as secondary protection',
      'Check accounts for unauthorized access before/after reset',
      'Blocking the domain alone doesn\'t fix credential theft',
    ],
    image: scenarioImages.email,
  },
  {
    id: 'ir-005',
    moduleType: 'incident-response',
    type: 'scenario',
    title: 'DDoS Attack in Progress',
    difficulty: 'intermediate',
    content: {
      scenario: 'Your company\'s e-commerce website is experiencing severe slowdowns. Monitoring shows traffic has spiked to 100x normal levels, mostly from IP addresses in multiple countries. Legitimate customers are unable to make purchases.',
      alertDetails: {
        trafficIncrease: '100x normal (10 Gbps)',
        sourceIPs: 'Distributed globally',
        affectedService: 'E-commerce platform',
        businessImpact: '$50,000/hour in lost sales',
      },
      question: 'What\'s the most effective immediate response?',
      options: [
        { id: 'a', text: 'Block all traffic from foreign countries', isCorrect: false },
        { id: 'b', text: 'Activate DDoS mitigation service and enable rate limiting', isCorrect: true },
        { id: 'c', text: 'Shut down the website until the attack stops', isCorrect: false },
        { id: 'd', text: 'Upgrade server capacity to handle the traffic', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [
      'Sudden 100x traffic spike',
      'Globally distributed sources = botnet',
      'Legitimate users impacted',
      'Significant financial impact',
    ],
    explanation: 'Contact your DDoS mitigation provider (Cloudflare, Akamai, AWS Shield) to absorb/filter malicious traffic. Implement rate limiting to slow down attack traffic while allowing some legitimate users through. Don\'t shut down completely - that\'s the attacker\'s goal.',
    learningPoints: [
      'Have DDoS mitigation services in place before attacks',
      'Rate limiting can help reduce impact',
      'Don\'t shut down - you\'re doing the attacker\'s job',
      'Document everything for post-incident review',
      'Consider law enforcement notification for major attacks',
    ],
    image: scenarioImages.security,
  },
  {
    id: 'ir-006',
    moduleType: 'incident-response',
    type: 'scenario',
    title: 'Lost Company Laptop',
    difficulty: 'beginner',
    content: {
      scenario: 'A sales representative reports their company laptop was stolen from their car overnight. The laptop contains customer contact information, sales proposals, and has saved credentials for Salesforce and company email.',
      alertDetails: {
        device: 'Dell Latitude laptop',
        data: 'Customer contacts, proposals, saved credentials',
        encryption: 'BitLocker enabled',
        lastSeen: 'Last night, 10 PM',
      },
      question: 'What steps should be taken to respond to this incident?',
      options: [
        { id: 'a', text: 'Wait to see if the laptop is recovered before taking action', isCorrect: false },
        { id: 'b', text: 'File a police report only since BitLocker is enabled', isCorrect: false },
        { id: 'c', text: 'Remote wipe the device, force password resets, revoke sessions, and file police report', isCorrect: true },
        { id: 'd', text: 'Order a replacement laptop for the employee', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [
      'Saved credentials = immediate account risk',
      'Customer data = potential breach notification requirements',
      'Physical theft = data potentially accessible',
      'BitLocker helps but isn\'t foolproof',
    ],
    explanation: 'Even with encryption, treat this as a potential breach. Remote wipe the device immediately. Force password resets for all accounts the user accessed. Revoke active sessions. File a police report for insurance and documentation. Assess if breach notification is required for customer data.',
    learningPoints: [
      'Remote wipe capability should be enabled on all devices',
      'Force password resets for all accounts on lost devices',
      'Revoke active sessions to log out stolen devices',
      'Encryption helps but assume data at risk',
      'Assess breach notification requirements for customer data',
    ],
    image: scenarioImages.warning,
  },
];
