// ============================================
// Threat Hunting Scenarios
// ============================================

import type { TrainingScenario } from './types';
import { scenarioImages } from './images';

export const threatHuntingScenarios: TrainingScenario[] = [
  {
    id: 'th-001',
    moduleType: 'threat-hunting',
    type: 'scenario',
    title: 'Analyze Suspicious PowerShell',
    difficulty: 'advanced',
    content: {
      scenario: 'Your SIEM flagged this PowerShell command executed on a workstation:\n\npowershell -encodedCommand JABjAGwAaQBlAG4AdAAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0AA==\n\nThe encoded portion decodes to: "$client = New-Object System.Net.WebClient"',
      alertDetails: {
        user: 'jsmith',
        workstation: 'DESKTOP-A1B2C3',
        time: '2:34 AM',
        process: 'powershell.exe',
      },
      question: 'What does this activity most likely indicate?',
      options: [
        { id: 'a', text: 'Normal IT maintenance activity', isCorrect: false },
        { id: 'b', text: 'User running a legitimate script for work', isCorrect: false },
        { id: 'c', text: 'Potential malware using encoded commands to evade detection', isCorrect: true },
        { id: 'd', text: 'Windows Update process', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [
      'Encoded PowerShell commands (Base64)',
      'Execution at 2:34 AM (off-hours)',
      'WebClient object = downloading content',
      'PowerShell execution policy bypass attempts',
    ],
    explanation: 'Attackers use encoded PowerShell to evade basic detection. The WebClient object downloads files from the internet - likely second-stage malware. The 2 AM execution time is suspicious. This pattern (encoded PowerShell + WebClient + off-hours) is a strong indicator of compromise.',
    learningPoints: [
      'Encoded commands are used to evade detection',
      'WebClient in PowerShell often downloads malware',
      'Off-hours execution is suspicious',
      'Look for PowerShell execution with -encodedCommand',
      'Correlate with other events on the same host',
    ],
    image: scenarioImages.hacker,
  },
  {
    id: 'th-002',
    moduleType: 'threat-hunting',
    type: 'scenario',
    title: 'DNS Anomaly Detection',
    difficulty: 'advanced',
    content: {
      scenario: 'Network monitoring shows a single workstation making 500+ DNS queries per minute to subdomains of "x7k9p2m.com" like "a1b2c3.x7k9p2m.com", "d4e5f6.x7k9p2m.com", etc. The domain was registered yesterday.',
      alertDetails: {
        queriesPerMinute: '500+',
        domain: 'x7k9p2m.com',
        domainAge: '1 day',
        subdomains: 'Random alphanumeric patterns',
      },
      question: 'What type of attack does this pattern suggest?',
      options: [
        { id: 'a', text: 'DDoS attack targeting a DNS server', isCorrect: false },
        { id: 'b', text: 'DNS tunneling/exfiltration - data hidden in DNS queries', isCorrect: true },
        { id: 'c', text: 'Normal CDN traffic with many subdomains', isCorrect: false },
        { id: 'd', text: 'DNS cache poisoning attempt', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [
      'Extremely high DNS query volume',
      'Newly registered domain (1 day old)',
      'Random alphanumeric subdomain patterns',
      'Data encoded in subdomain names',
    ],
    explanation: 'DNS tunneling encodes data in DNS queries to exfiltrate information or establish command-and-control channels. The random subdomains likely contain encoded stolen data. Newly registered domains with high query volumes are strong indicators of malicious C2 infrastructure.',
    learningPoints: [
      'DNS tunneling hides data in DNS queries',
      'High volumes of queries to one domain is suspicious',
      'Newly registered domains are higher risk',
      'Random subdomain patterns suggest encoded data',
      'Monitor for unusual DNS patterns in your environment',
    ],
    image: scenarioImages.security,
  },
  {
    id: 'th-003',
    moduleType: 'threat-hunting',
    type: 'scenario',
    title: 'Lateral Movement Detection',
    difficulty: 'advanced',
    content: {
      scenario: 'Authentication logs show user "admin_backup" successfully logged into 47 different servers within 10 minutes using RDP. This account normally only accesses 3 specific backup servers.',
      alertDetails: {
        account: 'admin_backup',
        serversAccessed: '47',
        timeWindow: '10 minutes',
        normalBaseline: '3 servers',
        protocol: 'RDP',
      },
      question: 'What threat behavior does this pattern indicate?',
      options: [
        { id: 'a', text: 'Routine backup operations', isCorrect: false },
        { id: 'b', text: 'Lateral movement - attacker using stolen credentials to spread', isCorrect: true },
        { id: 'c', text: 'IT performing emergency maintenance', isCorrect: false },
        { id: 'd', text: 'Account synchronization process', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [
      'Massive deviation from normal behavior (3 → 47 servers)',
      'Rapid access pattern (47 servers in 10 minutes)',
      'Service account used interactively',
      'Privileged account (admin_backup)',
    ],
    explanation: 'This is classic lateral movement behavior. An attacker compromised credentials and is rapidly spreading through the network. Service accounts accessing many more systems than baseline, especially quickly, strongly indicates attacker activity. Disable the account and investigate immediately.',
    learningPoints: [
      'Baseline normal behavior to detect anomalies',
      'Lateral movement shows rapid multi-system access',
      'Service accounts shouldn\'t have interactive logins',
      'Privileged accounts are high-value targets',
      'Speed of access is a key indicator',
    ],
    image: scenarioImages.hacker,
  },
  {
    id: 'th-004',
    moduleType: 'threat-hunting',
    type: 'scenario',
    title: 'Persistence Mechanism',
    difficulty: 'advanced',
    content: {
      scenario: 'During routine threat hunting, you find this registry key was created:\n\nHKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\nName: "WindowsUpdate"\nValue: "C:\\Users\\Public\\svchost.exe -hidden"\n\nThe file svchost.exe in the Public folder is 47KB.',
      alertDetails: {
        registryPath: 'HKCU\\...\\Run',
        valueName: 'WindowsUpdate (fake name)',
        executable: 'C:\\Users\\Public\\svchost.exe',
        fileSize: '47KB (real svchost is ~50KB in System32)',
      },
      question: 'What has the attacker accomplished here?',
      options: [
        { id: 'a', text: 'Installed a Windows Update helper', isCorrect: false },
        { id: 'b', text: 'Established persistence - malware will start automatically', isCorrect: true },
        { id: 'c', text: 'Optimized system startup', isCorrect: false },
        { id: 'd', text: 'Created a backup of svchost', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [
      'Run key = starts on user login (persistence)',
      'Fake "WindowsUpdate" name to blend in',
      'svchost.exe in wrong location (should be System32)',
      '"-hidden" parameter is suspicious',
      'Users\\Public is writable by anyone',
    ],
    explanation: 'This is a persistence mechanism. The Run registry key ensures the malware starts every time the user logs in. The attacker named it "WindowsUpdate" and "svchost.exe" to look legitimate. Real svchost.exe lives in System32, not Users\\Public. This survives reboots.',
    learningPoints: [
      'Run keys are common persistence locations',
      'Attackers use legitimate-sounding names',
      'svchost.exe should only be in System32',
      'Check for executables in unusual locations',
      'Persistence = malware survives reboots',
    ],
    image: scenarioImages.security,
  },
  {
    id: 'th-005',
    moduleType: 'threat-hunting',
    type: 'scenario',
    title: 'Beaconing Detection',
    difficulty: 'advanced',
    content: {
      scenario: 'Network analysis reveals a workstation making HTTPS connections to an external IP every exactly 3600 seconds (1 hour), 24/7, for the past 2 weeks. The data transferred is small (< 1KB each time).',
      alertDetails: {
        interval: 'Exactly 3600 seconds',
        duration: '2 weeks, 24/7',
        dataSize: '<1KB per connection',
        destination: 'External IP, no reverse DNS',
      },
      question: 'What does this perfectly regular pattern indicate?',
      options: [
        { id: 'a', text: 'Normal software checking for updates', isCorrect: false },
        { id: 'b', text: 'Command-and-control beaconing from malware', isCorrect: true },
        { id: 'c', text: 'Time synchronization service', isCorrect: false },
        { id: 'd', text: 'Cloud backup service', isCorrect: false },
      ],
    },
    isCorrectAnswer: true,
    redFlags: [
      'Perfectly regular intervals (exactly 3600s)',
      'Continuous 24/7 operation including nights/weekends',
      'Small data size (checking in, not large transfers)',
      'External IP with no reverse DNS',
      '2 weeks of persistent communication',
    ],
    explanation: 'This is C2 beaconing. Malware "phones home" at regular intervals to check for commands. The perfect timing, continuous operation, small data sizes, and unknown destination are classic indicators. Legitimate software has more variable timing. Investigate the workstation immediately.',
    learningPoints: [
      'C2 beaconing shows regular, predictable patterns',
      'Perfect intervals are more suspicious than variable',
      'Small, regular data transfers = check-ins',
      'Continuous 24/7 activity (even nights) is abnormal',
      'Investigate unknown external destinations',
    ],
    image: scenarioImages.hacker,
  },
];
